#!/bin/bash

#SBATCH --job-name=popacross2
#SBATCH --output=popacross2.out
#SBATCH --error=popacross2.err
#SBATCH --partition=long
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=20gb
#SBATCH --time=100:00:00

source /private/groups/kaylab/aschjeld/setup_conda.sh
conda activate popoolation2

# since this workflow is ACROSS populations, we will be utilizing the already created bam and bai files and jump straight into samtools mpileup!

POPDIR=/private/groups/kaylab/popoolation2/populations/gi/popoolation2_1201
BAMDIR=/private/groups/kaylab/popoolation2/populations/gi
SYNC=$BAMDIR/popacross/p_w.sync

cd $BAMDIR/popacross

# skipping to FET because everything else was completed before this 

# Use Fisher's Exact Test to calculate Fst
    perl "$POPDIR"/fisher-test.pl \
      --input "$SYNC" \
      --output p_w2.fet \
      --min-count 6 \
      --min-coverage 20 \
      --max-coverage 200 \
      --suppress-noninformative
echo "Fisher test to calculate Fst done" 

# convert the above to IGV file format
    perl "$POPDIR"/export/pwc2igv.pl \
      --input p_w2.fet \
      --output p_w_fet2.igv
  
echo "Fst for genes converting" 

# Calculate Fst for every gene
    perl "$POPDIR"/create-genewise-sync.pl \
      --input "$SYNC" \
      --gtf 2R_exons.gtf \
      --output p_w_genes.sync 

    perl "$POPDIR"/fst-sliding.pl \
      --min-count 6 \
      --min-coverage 20 \
      --max-coverage 200 \
      --pool-size 100 \
      --min-covered-fraction 0.6 \
      --window-size 1000000 \
      --step-size 1000000 \
      --input p_w_genes.sync \
      --output p_w_genewise.fst

echo "pipeline complete"
